name: roadradar_app
description: Road hazard reporting demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_map_marker_cluster: ^8.1.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  image_picker: ^1.2.0
  latlong2: ^0.9.1
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.3

flutter_localizations:
    sdk: flutter
    provider: ^6.1.5

  # UI / device
    cupertino_icons: ^1.0.8
    google_maps_flutter: ^2.12.3
    geolocator: ^14.0.2
    image_picker: ^1.1.2

  # Firebase
    firebase_core: ^4.0.0
    cloud_firestore: ^6.0.0
    firebase_storage: ^13.0.0
    firebase_auth: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
